apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
        branch: main
      - cluster: autopilot
        url: https://35.221.157.70
        branch: dev
  template:
    metadata:
      name: '{{branch}}-guestbook'
    spec:
      project: default
      source:
        repoURL: git@github.com:javalove93/my-argocd-examples.git
        targetRevision: '{{branch}}'
        path: application-sets/guestbook/
      destination:
        server: '{{url}}'
        namespace: appset
